### ISSUE TITLE
how to use in tauri v2?

### ISSUE THREAD

**Issue by kitty-eu-org** [amrbashir/system_tray#102]
how to use in tauri v2?

**Comment by FabianLars** [comment]
In Tauri's you'd use tauri's [tray module](https://docs.rs/tauri/2.0.0-alpha.18/tauri/tray/index.html), the only real docs for that are in the migration guide for now: https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#migrate-to-tray-icon-module
