### ISSUE TITLE
using gtk4?

### ISSUE THREAD

**Issue by TornaxO7** [amrbashir/system_tray#107]
`tray-icon` is currently using `gtk3`. Would it be possible to bump to `gtk4`?

**Comment by FabianLars** [comment]
Hi, i really wish we could do it. The tray library is tauri's biggest gtk4 blocker afaik (except for the work of upgrading😅) but unfortunetely libappindicator, the linux tray library, requires gtk3 and won't update to gtk4 anytime soon ([ref](https://github.com/AyatanaIndicators/libayatana-appindicator/issues/22)) especially considering that many distros still only use the "old" library (the one without ayatana in its name) which is basically unmaintained.

So i guess it's more likely we'll drop libappindicator for knsi or something at some point than using gtk4.

**Comment by TornaxO7** [comment]
Damn it... may I ask if you know any alternatives to create system trays with rust?

**Comment by FabianLars** [comment]
There's a rust implementation for ksni here https://github.com/iovxw/ksni but i don't know how usable it is.

**Comment by TornaxO7** [comment]
thank you for the information!

**Comment by nazar-pc** [comment]
Why not using https://github.com/iovxw/ksni on Linux then? Looks like a decent selection of supported specs and no GTK stuff in dependencies.

**Comment by FabianLars** [comment]
Well, that was the plan all the way back (iirc even before we moved out the tray implementation from tauri/tao into this crate) but we don't have time for this right now. We of course wouldn't turn down PRs in the meantime.

**Comment by nazar-pc** [comment]
Will experiment with it in our project and if it works well might send a PR your way, thanks!
