### ISSUE TITLE
It is not clear how to use it

### ISSUE THREAD

**Issue by Andrew-web-coder** [amrbashir/system_tray#116]
So, I copy/paste code from the `Examples`:

```js
use tray_icon::TrayIconBuilder;

let tray_icon = TrayIconBuilder::new()
    .with_tooltip("system-tray - tray icon library!")
    .with_icon(icon)
    .build()
    .unwrap();
```

And, unsuprisingly, I got 

```
unresolved import `tray_icon`
use of undeclared crate or module `tray_icon`

cannot find value `icon` in this scope
not found in this scope
```

What am I missing? I do not see any extra steps in the readme. 

Then, I hoped to get answer in `example` folder, but ... there are multiple files - 1) I do not understand why there are many of them and what is the difference; 2) I copied code snippets and none of them worked for me, again, something is missing.

**Comment by Andrew-web-coder** [comment]
The next question would be - how to add icon to the menu item...

**Comment by amrbashir** [comment]
you need to add the crate to your `Cargo.toml` or just run `cargo add tray-icon` in your Rust project.

**Comment by amrbashir** [comment]
> The next question would be - how to add icon to the menu item...

For that you'd need to attach a menu to your tray icon, see https://github.com/tauri-apps/tray-icon/blob/13cabcd5184e7721c42c2c1262af5e0468146003/examples/tao.rs#L19-L42

**Comment by Andrew-web-coder** [comment]
@amrbashir Thanks, but I was thinking about the icon next to the menu item in the tray (for example, [X] icon next to the Quit item), not the tray itself.

**Comment by amrbashir** [comment]
yes, you will need to use https://docs.rs/tray-icon/latest/tray_icon/menu/struct.IconMenuItem.html

**Comment by Andrew-web-coder** [comment]
But, if I use code from docs - https://tauri.app/v1/guides/features/system-tray/ - then I can not use IconMenuItem :/

**Comment by amrbashir** [comment]
that's because these are different types and different versions. Also icon menu items are not supported in v1.
