### ISSUE TITLE
Error from simple example: "assertion 'GDK_IS_SCREEN (screen)' failed"

### ISSUE THREAD

**Issue by dscottboggs** [amrbashir/system_tray#13]
Output:
~~~
(process:70403): Gtk-CRITICAL **: 08:18:12.185: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:70403): GLib-GObject-WARNING **: 08:18:12.187: invalid (NULL) pointer instance

(process:70403): GLib-GObject-CRITICAL **: 08:18:12.187: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
~~~

system info

(removed)

---

A minimal example can be found [here](https://github.com/dscottboggs/problem-example)

I'm suspecting there's some dependency I need that isn't specified? I've added a `PKGBUILD` to the repo to demonstrate that I'm depending on `xdo`, is there something else I need?

**Comment by amrbashir** [comment]
Looking at your repo, you probably need to init a gtk loop on the thread before creating the tray icon, either by manually calling `gtk::init` or just using a crate for event loop like `winit` or `tao`. See the `examples` directory in the repo.
