### ISSUE TITLE
Can I add some items for Submenu while the program is running?

### ISSUE THREAD

**Issue by LeeeSe** [amrbashir/system_tray#176]
I cannot determine which items should be included in the Submenu during program initialization. It depends on the state of the computer at that time. After consulting the documentation, I found that currently, I can only add or remove an entire menu item.

Is there a way to add some items to the Submenu during the program’s runtime?

**Comment by amrbashir** [comment]
you can add/remove items from a submenu without a problem, for example:
```rs
let tray_menu = Menu::new(); // or Submenu::new();

let tray_icon = TrayIconBuilder::new()
    .with_menu(Box::new(tray_menu.clone()))
    .with_tooltip("system-tray - tray icon library!")
    .with_icon(icon)
    .build()
    .unwrap();
```

then later on in your program you can  do
```rs
tray_menu.append();
tray_menu.remove();
```
