### ISSUE TITLE
Support running without a windowing framework

### ISSUE THREAD

**Issue by JerwuQu** [amrbashir/system_tray#198]
The `tray-icon` event receivers rely on another library (or manual implementation) to churn a event loop. It would be nice if the library could take care of this itself.

Getting it working on Windows just required the following:
```rust
loop {
    unsafe {
        let mut msg: MSG = std::mem::zeroed();
        while PeekMessageW(&mut msg, null_mut(), 0, 0, 1) > 0 {
            TranslateMessage(&msg);
            DispatchMessageW(&msg);
        }
    }

    ...handle tray events...
    ...maybe sleep a bit...
}

```

**Comment by amrbashir** [comment]
The tray-icon crate works without a windowing framework, you just need bring your event loop, whether that comes from winit, tao, egui, or manual event loop in that case.

This crate only concern is to create the tray and handle its events. That's it, simple and to the point. Making an event loop built-in is reinventing the wheel as there is a lot of GUI event loop out there.

If your aim is minimalist event loop, I think it might be a good choice to write another crate and I will happily mention it in the docs and add examples.
