### ISSUE TITLE
Can we just show text(without icon) in menubar?

### ISSUE THREAD

**Issue by 2nthony** [amrbashir/system_tray#21]
https://github.com/matryer/xbar, image below is how xbar shows.
![image](https://user-images.githubusercontent.com/19513289/217488120-f0a51c72-a50c-4aed-bccb-e57db8456dc2.png)

I am building an app using tauri-app, I just want to show text.

I've tried to set an empty png as icon(1px transparent), but throw error about `not visible`

```sh
thread 'main' panicked at 'error while running tauri application: Runtime(InvalidIcon(ByteCountNotDivisibleBy4 { byte_count: 5 }))', src/main.rs:39:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So can we support pure text or support empty png 🤔?

**Comment by amrbashir** [comment]
Just noting that this crate is not used by tauri just yet. 

Here is the method you need https://docs.rs/tray-icon/latest/tray_icon/struct.TrayIconBuilder.html#method.with_title and you don't need to provide an icon at all (unless you're are on linux then you'd need to provide a transparent icon that conforms to the rules here https://docs.rs/tray-icon/latest/tray_icon/icon/struct.Icon.html#method.from_rgba)
