### ISSUE TITLE
Consider renaming the project to system-tray for consistency with other tauri crates

### ISSUE THREAD

**Issue by fgimian** [amrbashir/system_tray#3]
My OCD couldn't help but notice that this was the only project that used an underscore in both the repo and crate name. 🤣   I believe that all other tauri libraries (and most of the Rust ecosystem) prefers dashes, so thought I'd raise this since it may be a good time to adjust the name before the crate is released. 😄 

Cheers
Fotis

**Comment by amrbashir** [comment]
This is definitely a temporary name; it will not probably be called system_tray since there is other crates with this name anyways. Any suggestions are welcome!

**Comment by fgimian** [comment]
Thanks heaps for the reply.  I actually don't believe there is a crate called system-tray at the moment, see https://crates.io/crates/system-tray 😄

**Comment by amrbashir** [comment]
I could swear I saw a similar crate on crates.io or GitHub, well, doesn't matter, we will probably choose another name (probably from jojo, similar to https://github.com/tauri-apps/muda)

**Comment by amrbashir** [comment]
crate has been renamed to `tray-icon` for now.
