### ISSUE TITLE
Clarification on dependencies

### ISSUE THREAD

**Issue by mars1211** [amrbashir/system_tray#32]
Are the specified dependencies for development purposes only?

> Arch Linux / Manjaro:
pacman -S gtk3 libappindicator-gtk3 #or libayatana-appindicator
Debian / Ubuntu:
sudo apt install libgtk-3-dev libappindicator3-dev #or libayatana-appindicator3-dev

**Comment by FabianLars** [comment]
Nope, they are needed for development and on the user's system.

To be clear: the dev system needs the *-dev package and the user system needs the non-dev runtime package.
