### ISSUE TITLE
set_visible(false)  still occupying position

### ISSUE THREAD

**Issue by LeeeSe** [amrbashir/system_tray#36]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/44465325/230507924-6349ee74-9c25-4045-86be-c51bef5e106c.png">

Is there a solution? Or is it unavoidable?

**Comment by amrbashir** [comment]
@LeeeSe Could you test #37 and see if it fixes the issue for you?

**Comment by LeeeSe** [comment]
work for me
