### ISSUE TITLE
feat: query the tray icon rect without waiting for an event

### ISSUE THREAD

**Issue by sdr0x07b6** [amrbashir/system_tray#86]
The system tray is created for macOS.
Clicking on the system tray opens a window at the bottom of it.
The coordinates of the window are set using tauri-plugin-positioner.

The application can also display windows with global shortcut keys.
I was able to implement the shortcut key display, but I am having trouble setting the coordinates.
If I do nothing, the window will be centered on the display, so when I execute `window.move_window(Position::TrayCenter);`, it crashes.

When the user clicks on the system tray on the menu bar, a system tray event is fired at that point, so tauri-plugin-positioner can calculate where it should appear.
However, it is possible that a user may use a shortcut key without ever clicking on the system tray after launching an application. At that time, the system tray event has not yet occurred, so tauri-plugin-positioner cannot calculate where the window should be displayed. That's why I think that executing `window.move_window(Position::TrayCenter);` in the display handler will cause a crash.

Do you have any ideas that could solve this?
Also, fundamentally, do you think Tauri itself needs to be improved so that it can calculate the display coordinates when the system tray is activated?

**Comment by pronebird** [comment]
I need this very much as well, please add support for retrieving tray icon rect without waiting for an event.
