### ISSUE TITLE
How to use MenuItem on Linux?

### ISSUE THREAD

**Issue by zkxs** [amrbashir/system_tray#99]
I'm trying to interact with a CheckMenuItem on the event loop in Linux, and I can't figure out how because of the following requirements:
- the tray icon must be built on the GTK thread
- the menu items must be passed in when the tray icon is built, therefore they must also be on the GTK thread
- the GTK thread and the event loop must be different threads, as calling `gtk:main()` takes over the GTK thread forever
- neither TrayIcon nor MenuItem are Send, so I can't move them between the GTK thread and the event loop thread.

I'm sure I'm missing something, but it looks impossible for the event loop to interact with MenuItems on Linux. If the examples could be updated to show how this is supposed to be done I'd appreciate it!

**Comment by amrbashir** [comment]
instead of calling `gtk::main`, you can create a loop and call `gtk::main_iteration_do`, and you can pair that with a channel to send requests from the main thread to and listen to it on the gtk thread so it modifies the menu.
